/**
 * Sample transaction payloads used to seed the Predict form with one
 * click. Each example exercises a different region of the input space
 * so the demo can show the dummy/real model reacting to risk signals.
 */

import type { TransactionRequest } from "@/types";

/** Low-risk grocery purchase from the cardholder's usual location. */
export const LEGIT_EXAMPLE: TransactionRequest = {
  transaction_amount: 42.5,
  transaction_hour: 14,
  transaction_day_of_week: 2,
  is_weekend: 0,
  merchant_category: "groceries",
  transaction_type: "purchase",
  card_type: "visa",
  transaction_count_24h: 2,
  transaction_count_7d: 8,
  avg_transaction_amount_30d: 50.0,
  amount_to_avg_ratio: 0.85,
  unique_merchants_7d: 4,
  is_first_transaction_merchant: 0,
  distance_from_home_km: 2.1,
  is_foreign_transaction: 0,
  is_high_risk_country: 0,
  device_type: "mobile",
  browser_type: "app",
  ip_risk_score: 0.05,
  account_age_days: 720,
  user_age: 36,
  credit_limit: 5000.0,
  credit_utilization: 0.18,
  previous_fraud_flag: 0,
  log_amount: Math.log1p(42.5),
  is_high_velocity: 0,
  is_new_account: 0,
  is_late_night: 0,
  amount_z_score: -0.15,
};

/** Mid-risk — large electronics purchase from a slightly unusual location. */
export const SUSPICIOUS_EXAMPLE: TransactionRequest = {
  transaction_amount: 850.0,
  transaction_hour: 22,
  transaction_day_of_week: 5,
  is_weekend: 0,
  merchant_category: "electronics",
  transaction_type: "purchase",
  card_type: "mastercard",
  transaction_count_24h: 4,
  transaction_count_7d: 18,
  avg_transaction_amount_30d: 120.0,
  amount_to_avg_ratio: 7.0,
  unique_merchants_7d: 8,
  is_first_transaction_merchant: 1,
  distance_from_home_km: 280.0,
  is_foreign_transaction: 0,
  is_high_risk_country: 0,
  device_type: "desktop",
  browser_type: "chrome",
  ip_risk_score: 0.45,
  account_age_days: 180,
  user_age: 29,
  credit_limit: 4000.0,
  credit_utilization: 0.62,
  previous_fraud_flag: 0,
  log_amount: Math.log1p(850.0),
  is_high_velocity: 1,
  is_new_account: 0,
  is_late_night: 1,
  amount_z_score: 2.4,
};

/** High-risk — foreign cash advance at 3 AM from a brand-new account. */
export const FRAUD_EXAMPLE: TransactionRequest = {
  transaction_amount: 1500.0,
  transaction_hour: 3,
  transaction_day_of_week: 6,
  is_weekend: 1,
  merchant_category: "online",
  transaction_type: "cash_advance",
  card_type: "visa",
  transaction_count_24h: 9,
  transaction_count_7d: 25,
  avg_transaction_amount_30d: 75.0,
  amount_to_avg_ratio: 20.0,
  unique_merchants_7d: 14,
  is_first_transaction_merchant: 1,
  distance_from_home_km: 5800.0,
  is_foreign_transaction: 1,
  is_high_risk_country: 1,
  device_type: "desktop",
  browser_type: "unknown",
  ip_risk_score: 0.93,
  account_age_days: 4,
  user_age: 21,
  credit_limit: 1500.0,
  credit_utilization: 0.95,
  previous_fraud_flag: 1,
  log_amount: Math.log1p(1500.0),
  is_high_velocity: 1,
  is_new_account: 1,
  is_late_night: 1,
  amount_z_score: 4.8,
};
